export const SET_CURRENT_LANG = 'SET_CURRENT_LANG';
export const GET_CURRENT_LANG = 'GET_CURRENT_LANG';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA = 'FETCH_DATA';
export const STORE_LEADS_LIST = "STORE_LEADS_LIST";
export const GET_LEAD_DETAILS = "GET_LEAD_DETAILS"